import type { Question } from "./types";

export const QUESTION_BANK: Question[] = [
  {
    id: "um-e-01",
    subject: "Physics",
    grade: "11",
    chapter: "units-and-measurements",
    chapterTitle: "Units and Measurements",
    topic: "SI units",
    type: "MCQ",
    difficulty: "Easy",
    stem: "The SI unit of luminous intensity is",
    options: ["lux", "candela", "lumen", "watt"],
    answer: "candela",
    solution: "The seven SI base units include candela (cd) for luminous intensity.",
    marks: 1,
    verified: true,
  },
  {
    id: "um-e-02",
    subject: "Physics",
    grade: "11",
    chapter: "units-and-measurements",
    chapterTitle: "Units and Measurements",
    topic: "Significant figures",
    type: "MCQ",
    difficulty: "Easy",
    stem: "The number of significant figures in 0.00240 is",
    options: ["2", "3", "4", "5"],
    answer: "3",
    solution: "Leading zeros are not significant. 2, 4 and the trailing zero after the decimal are significant, so 3.",
    marks: 1,
    verified: true,
  },
  {
    id: "um-e-03",
    subject: "Physics",
    grade: "11",
    chapter: "units-and-measurements",
    chapterTitle: "Units and Measurements",
    topic: "Dimensions",
    type: "FITB",
    difficulty: "Easy",
    stem: "The dimensional formula of force is ________.",
    answer: "[MLT^{-2}]",
    solution: "F = ma. [m] = [M], [a] = [LT^{-2}], so [F] = [MLT^{-2}].",
    marks: 1,
    verified: true,
  },
  {
    id: "um-m-01",
    subject: "Physics",
    grade: "11",
    chapter: "units-and-measurements",
    chapterTitle: "Units and Measurements",
    topic: "Dimensional analysis",
    type: "MCQ",
    difficulty: "Medium",
    stem: "Which of the following pairs have the same dimensions?",
    options: [
      "Torque and work",
      "Force and energy",
      "Momentum and impulse of force / time",
      "Pressure and force",
    ],
    answer: "Torque and work",
    solution:
      "Torque = r × F → [ML^{2}T^{-2}]. Work = F·s → [ML^{2}T^{-2}]. Same dimensions; they are still different physical quantities.",
    marks: 1,
    verified: true,
  },
  {
    id: "um-m-02",
    subject: "Physics",
    grade: "11",
    chapter: "units-and-measurements",
    chapterTitle: "Units and Measurements",
    topic: "Errors",
    type: "NAT",
    difficulty: "Medium",
    stem: "The percentage error in measuring mass and speed are 2% and 3% respectively. The maximum percentage error in kinetic energy (½mv²) is",
    answer: "8",
    solution: "ΔKE/KE = Δm/m + 2(Δv/v) = 2% + 2×3% = 8%.",
    marks: 2,
    verified: true,
  },
  {
    id: "um-m-03",
    subject: "Physics",
    grade: "11",
    chapter: "units-and-measurements",
    chapterTitle: "Units and Measurements",
    topic: "Least count",
    type: "FITB",
    difficulty: "Medium",
    stem: "A screw gauge has a pitch of 1 mm and 100 divisions on the circular scale. Its least count is ________ mm.",
    answer: "0.01",
    solution: "Least count = pitch / number of divisions = 1 mm / 100 = 0.01 mm.",
    marks: 1,
    verified: true,
  },
  {
    id: "um-h-01",
    subject: "Physics",
    grade: "11",
    chapter: "units-and-measurements",
    chapterTitle: "Units and Measurements",
    topic: "Dimensions of physical constants",
    type: "MCQ",
    difficulty: "Hard",
    stem: "The dimensional formula of the universal gravitational constant G is",
    options: ["[M^{-1}L^{3}T^{-2}]", "[ML^{3}T^{-2}]", "[M^{-1}L^{2}T^{-2}]", "[MLT^{-2}]"],
    answer: "[M^{-1}L^{3}T^{-2}]",
    solution: "From F = Gm₁m₂/r², G = Fr²/m₁m₂ → [MLT^{-2}][L^{2}]/[M^{2}] = [M^{-1}L^{3}T^{-2}].",
    marks: 1,
    verified: true,
  },
  {
    id: "um-h-02",
    subject: "Physics",
    grade: "11",
    chapter: "units-and-measurements",
    chapterTitle: "Units and Measurements",
    topic: "Significant figures",
    type: "NAT",
    difficulty: "Hard",
    stem: "Add 2.3 × 10² and 4.15 × 10¹ and report the result with the correct number of significant figures in ordinary (non-scientific) form. Enter the integer value.",
    answer: "270",
    solution:
      "230 + 41.5 = 271.5. Limited by 2.3 × 10² (precision of 10), so rounded to 270.",
    marks: 2,
    verified: true,
  },
  {
    id: "ms-e-01",
    subject: "Physics",
    grade: "11",
    chapter: "motion-in-a-straight-line",
    chapterTitle: "Motion in a Straight Line",
    topic: "Average speed",
    type: "MCQ",
    difficulty: "Easy",
    stem: "A car travels 40 km in 30 min and another 40 km in 40 min. Its average speed for the whole journey is",
    options: ["60 km/h", "68.6 km/h", "80 km/h", "70 km/h"],
    answer: "68.6 km/h",
    solution: "Total distance = 80 km. Total time = 70 min = 7/6 h. Average speed = 80 ÷ (7/6) ≈ 68.6 km/h.",
    marks: 1,
    verified: true,
  },
  {
    id: "ms-e-02",
    subject: "Physics",
    grade: "11",
    chapter: "motion-in-a-straight-line",
    chapterTitle: "Motion in a Straight Line",
    topic: "Displacement vs distance",
    type: "FITB",
    difficulty: "Easy",
    stem: "Displacement can be zero even if distance is not zero because displacement is a ________ quantity.",
    answer: "vector",
    solution: "Displacement is the vector change in position. A round trip has zero displacement and non-zero distance.",
    marks: 1,
    verified: true,
  },
  {
    id: "ms-e-03",
    subject: "Physics",
    grade: "11",
    chapter: "motion-in-a-straight-line",
    chapterTitle: "Motion in a Straight Line",
    topic: "Equations of motion",
    type: "NAT",
    difficulty: "Easy",
    stem: "A body starts from rest and accelerates at 2 m/s² for 5 s. The distance travelled (in m) is",
    answer: "25",
    solution: "s = ut + ½at² = 0 + ½(2)(25) = 25 m.",
    marks: 1,
    verified: true,
  },
  {
    id: "ms-m-01",
    subject: "Physics",
    grade: "11",
    chapter: "motion-in-a-straight-line",
    chapterTitle: "Motion in a Straight Line",
    topic: "Relative velocity",
    type: "MCQ",
    difficulty: "Medium",
    stem: "Two trains each of length 100 m move in opposite directions at 40 km/h and 32 km/h. Time taken to cross each other is",
    options: ["5 s", "10 s", "12 s", "15 s"],
    answer: "10 s",
    solution:
      "Relative speed = 72 km/h = 20 m/s. Distance to cross = 200 m. t = 200/20 = 10 s.",
    marks: 1,
    verified: true,
  },
  {
    id: "ms-m-02",
    subject: "Physics",
    grade: "11",
    chapter: "motion-in-a-straight-line",
    chapterTitle: "Motion in a Straight Line",
    topic: "v–t graph",
    type: "FITB",
    difficulty: "Medium",
    stem: "The area under a velocity–time graph equals ________.",
    answer: "displacement",
    solution: "∫v dt over an interval is the change in position (displacement).",
    marks: 1,
    verified: true,
  },
  {
    id: "ms-m-03",
    subject: "Physics",
    grade: "11",
    chapter: "motion-in-a-straight-line",
    chapterTitle: "Motion in a Straight Line",
    topic: "Free fall",
    type: "NAT",
    difficulty: "Medium",
    stem: "A ball is thrown vertically upward with 20 m/s. Taking g = 10 m/s², the time (in s) to return to the thrower is",
    answer: "4",
    solution: "Time of flight = 2u/g = 40/10 = 4 s.",
    marks: 2,
    verified: true,
  },
  {
    id: "ms-h-01",
    subject: "Physics",
    grade: "11",
    chapter: "motion-in-a-straight-line",
    chapterTitle: "Motion in a Straight Line",
    topic: "Variable acceleration",
    type: "MCQ",
    difficulty: "Hard",
    stem: "The velocity of a particle is v = at + bt², where a and b are constants. The acceleration at t = 1 s is",
    options: ["a + 2b", "a + b", "2a + b", "a + 3b"],
    answer: "a + 2b",
    solution: "a(t) = dv/dt = a + 2bt. At t = 1 s, acceleration = a + 2b.",
    marks: 1,
    verified: true,
  },
  {
    id: "ms-h-02",
    subject: "Physics",
    grade: "11",
    chapter: "motion-in-a-straight-line",
    chapterTitle: "Motion in a Straight Line",
    topic: "Average velocity",
    type: "NAT",
    difficulty: "Hard",
    stem: "A particle moves 30 m east in 2 s and then 40 m north in 3 s. Magnitude of average velocity (in m/s) for the whole trip is",
    answer: "10",
    solution: "Net displacement = √(30² + 40²) = 50 m. Total time = 5 s. Average velocity = 50/5 = 10 m/s.",
    marks: 2,
    verified: true,
  },
  {
    id: "lm-e-01",
    subject: "Physics",
    grade: "11",
    chapter: "laws-of-motion",
    chapterTitle: "Laws of Motion",
    topic: "Newton's first law",
    type: "MCQ",
    difficulty: "Easy",
    stem: "Newton’s first law of motion defines",
    options: ["force", "inertia", "momentum", "acceleration"],
    answer: "inertia",
    solution: "The first law is the law of inertia: a body remains in its state unless acted on by a net external force.",
    marks: 1,
    verified: true,
  },
  {
    id: "lm-e-02",
    subject: "Physics",
    grade: "11",
    chapter: "laws-of-motion",
    chapterTitle: "Laws of Motion",
    topic: "Momentum",
    type: "FITB",
    difficulty: "Easy",
    stem: "The product of mass and velocity of a body is called ________.",
    answer: "momentum",
    solution: "Linear momentum p = mv.",
    marks: 1,
    verified: true,
  },
  {
    id: "lm-e-03",
    subject: "Physics",
    grade: "11",
    chapter: "laws-of-motion",
    chapterTitle: "Laws of Motion",
    topic: "F = ma",
    type: "NAT",
    difficulty: "Easy",
    stem: "A force of 10 N acts on a 2 kg mass. The acceleration (in m/s²) is",
    answer: "5",
    solution: "a = F/m = 10/2 = 5 m/s².",
    marks: 1,
    verified: true,
  },
  {
    id: "lm-m-01",
    subject: "Physics",
    grade: "11",
    chapter: "laws-of-motion",
    chapterTitle: "Laws of Motion",
    topic: "Impulse",
    type: "MCQ",
    difficulty: "Medium",
    stem: "Impulse of a force is equal to the change in",
    options: ["kinetic energy", "potential energy", "momentum", "acceleration"],
    answer: "momentum",
    solution: "J = ∫F dt = Δp. Impulse–momentum theorem.",
    marks: 1,
    verified: true,
  },
  {
    id: "lm-m-02",
    subject: "Physics",
    grade: "11",
    chapter: "laws-of-motion",
    chapterTitle: "Laws of Motion",
    topic: "Connected bodies",
    type: "NAT",
    difficulty: "Medium",
    stem: "Two masses 3 kg and 5 kg connected by a light string pass over a light frictionless pulley. Acceleration of the system in m/s² is (take g = 10)",
    answer: "2.5",
    solution: "a = (m₂ − m₁)g / (m₁ + m₂) = (2)(10)/8 = 2.5 m/s².",
    marks: 2,
    verified: true,
  },
  {
    id: "lm-m-03",
    subject: "Physics",
    grade: "11",
    chapter: "laws-of-motion",
    chapterTitle: "Laws of Motion",
    topic: "Friction",
    type: "FITB",
    difficulty: "Medium",
    stem: "The maximum value of static friction is μN, also called ________ friction.",
    answer: "limiting",
    solution: "Limiting friction f_L = μ_s N is the maximum static friction before slipping.",
    marks: 1,
    verified: true,
  },
  {
    id: "lm-h-01",
    subject: "Physics",
    grade: "11",
    chapter: "laws-of-motion",
    chapterTitle: "Laws of Motion",
    topic: "Apparent weight",
    type: "MCQ",
    difficulty: "Hard",
    stem: "A person of mass m stands in a lift accelerating upward with a. The apparent weight is",
    options: ["mg", "m(g − a)", "m(g + a)", "ma"],
    answer: "m(g + a)",
    solution: "Normal reaction N − mg = ma ⇒ N = m(g + a) when the lift accelerates up.",
    marks: 1,
    verified: true,
  },
  {
    id: "lm-h-02",
    subject: "Physics",
    grade: "11",
    chapter: "laws-of-motion",
    chapterTitle: "Laws of Motion",
    topic: "Recoil",
    type: "NAT",
    difficulty: "Hard",
    stem: "A gun of mass 5 kg fires a 50 g bullet at 200 m/s. Recoil speed of the gun (in m/s) is",
    answer: "2",
    solution: "m_b v_b = m_g v_g ⇒ 0.05 × 200 = 5 v_g ⇒ v_g = 2 m/s.",
    marks: 2,
    verified: true,
  },
];
